### ISSUE TITLE
ROR link treated as internal CMS page link

### ISSUE THREAD

**Issue by S-Haime** [openlibhums/janeway#4461]
It appears that the field for external ROR funder links is treated as if the input is an internal CMS page. E.g.:
`https://journal.org/funder_articles/https://ror.org/[RORCODE]` instead of `https://ror.org/[RORCODE]`. The link cannot resolve and does not function. This is suboptimal. It would be good to resolve this ASAP as funding information is important.

Version
1.7

To reproduce / for example in the wild:
https://journal.digitalmedievalist.org/article/id/15119/
Scroll down to 'Funding' 
![image](https://github.com/user-attachments/assets/c3c1102b-8601-4f70-9880-d5d72e71b254)
![image](https://github.com/user-attachments/assets/d301e453-3056-46ab-899d-236237915ddf)
![image](https://github.com/user-attachments/assets/eba730a5-61c3-449a-acee-5bb6cad9af8a)

Reported to FD #9304. Please update editor when resolved.

**Comment by ajrbyers** [comment]
This field may need to be tweaked to be more generic but an ROR code isn’t a Fundref ID.

**Comment by joemull** [comment]
After working on a fix, I believe the root problem of this one is that the hyperlink on the funder name is ambiguous:

https://github.com/openlibhums/janeway/blob/d387ba83e804f48b172bab866b5dffd20c986bb8/src/themes/clean/templates/journal/article.html#L129

1. Users do not know where the link will go.
2. The link does not work before the article is published, so it is impossible to proofread.
3. Once they arrive, there is no information to explain the page they are seeing.
4. It just says "Articles" and has the typical filters, none of which relate to funders. Example from Glossa:
  
  ![image](https://github.com/user-attachments/assets/357418ea-9e41-4747-a7fd-39a8b163ec28)

The Digital Medievalist editors assumed it would go to a page with a record for that funder. But in many cases the FundrefID URL we populate there is a JSON API page, so that is not suitable.

The user in the reported case put an ROR link there, which makes perfect sense and would provide a human-readable page because the ROR website is quite good that way. But until we have ROR integrated (#3168), we can't offer that user journey in a reliable way.

**Comment by ajrbyers** [comment]
Closed by https://github.com/openlibhums/janeway/pull/4464
