### ISSUE TITLE
Deprecated template will error out

### ISSUE THREAD

**Issue by ajrbyers** [openlibhums/janeway#4526]
We've marked the public profile templates as deprecated through a comment to let people know we will be removing them if they are still using them. However, the `{% comment %}` tag at the top of the file will cause them to error out which we don't want.

https://github.com/openlibhums/janeway/blob/bf7683deff1fa5f1ca27781aeb41d50336d17f39/src/themes/OLH/templates/core/accounts/public_profile.html#L1-L7

THis needs to be updated on:

- [x] OLH
- [x] Clean
- [x] Material

A PR is open on Hourglass: https://github.com/openlibhums/hourglass/pull/417

**Comment by joemull** [comment]
Thank you for catching this. 

I think there are two problems:

- The deprecation comment should come after the extend on this _and other_ templates. It was put in this spot for several dozen templates, but only this one is showing up as an error for users, because...

- This template should not have been marked as deprecated at all, because it is the public facing profile for a user, and it should feel like part of the site's CMS content.
